name: github-CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      NEXT_PUBLIC_GOOGLE_MAPS_KEY_DEMO: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_KEY_DEMO }}

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24.14.1"
          cache: "npm"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
